title: "Zachary Leighton"
description: "Zachary Leighton LTD | "
about: "Personal Site"
location: "Netanya, Israel"
email: your-email@example.com
baseurl: "/zleight1.github.io"

url: "http://zleight1.github.io" # replace by your site's url
github_username:  zleight1
author: "Zachary Leighton"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
